<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="base_diameter" value="0.4" />
    <xacro:property name="base_length" value="0.15" /> <!-- Length - wysokosc podstawy -->
    <xacro:property name="wheel_radius" value="0.1" />
    <xacro:property name="wheel_length" value="0.05" />
    <xacro:property name="turret_radius" value="0.05" />
    <xacro:property name="turret_length" value="0.2" />

    
    <link name="base_footprint" />

    <link name="base_link">
        <visual>
            <geometry>
                <cylinder radius="${base_diameter / 2.0}" length="${base_length}"/>
            </geometry>
            <origin xyz="0 0 ${base_length / 2.0}" rpy="0 0 0" />
            <material name="black" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${base_diameter / 2.0}" length="${base_length}"/>
            </geometry>
            <origin xyz="0 0 ${base_length / 2.0}" rpy="0 0 0" />    
        </collision>
        <xacro:cylinder_inertia m="5.0" r="${base_diameter / 2.0}" h="${base_length}" 
                                xyz="0 0 ${base_length / 2.0}" rpy="0 0 0" />        
    </link>

    <link name="turret_link">
        <visual>
            <geometry>
                <cylinder radius="${turret_radius}" length="${turret_length}"/>
            </geometry>
            <origin xyz="0 0 0.1" rpy="0 0 0"/>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${turret_radius}" length="${turret_length}"/>
            </geometry>
            <origin xyz="0 0 0.1" rpy="0 0 0"/>        
        </collision>
        <xacro:cylinder_inertia m="1.0" r="${turret_radius}" h="${turret_length}" 
                                xyz="0 0 0.1" rpy="0 0 0" />            
    </link>

    <link name="turret_top_link">
        <visual>
            <geometry>
                <cylinder radius="${turret_radius + 0.01}" length="${turret_radius}"/> 
            </geometry>
            <origin xyz="0 0 0.05" rpy="0 0 0"/> 
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${turret_radius + 0.01}" length="${turret_radius}"/> 
            </geometry>
            <origin xyz="0 0 0.05" rpy="0 0 0"/>         
        </collision>        
        <xacro:cylinder_inertia m="0.2" r="${turret_radius + 0.01}" h="${turret_radius}" 
                                xyz="0 0 0.05" rpy="0 0 0" />        
    </link>

    <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
                <material name="grey" />
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />    
            </collision>            
            <xacro:cylinder_inertia m="1.0" r="${wheel_radius}" h="${wheel_length}" 
                                    xyz="0 0 0" rpy="${pi / 2.0} 0 0" />        
        </link>           
    </xacro:macro>

    <xacro:wheel_link prefix="right" />
    <xacro:wheel_link prefix="left" />


    <link name="caster_wheel_link">
        <visual>
            <geometry>
                <sphere radius="${(wheel_radius + 0.02) / 2.0}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="grey" />
        </visual>
        <collision>
            <geometry>
                <sphere radius="${(wheel_radius + 0.02) / 2.0}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />        
        </collision>
        <xacro:sphere_inertia m="5.0" r="${(wheel_radius + 0.02) / 2.0}"
                              xyz="0 0 0" rpy="0 0 0" />
    </link>

    <joint name="base_joint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
    </joint>

    <joint name="base_turret_joint" type="fixed">
        <parent link="base_link"/>
        <child link="turret_link"/>
        <origin xyz="0 0 ${base_length}" rpy="0 0 0"/>
    </joint>

    <joint name="turret_top_joint" type="fixed">
        <parent link="turret_link"/>
        <child link="turret_top_link"/>
        <origin xyz="0 0 0.175" rpy="0 0 0"/>
    </joint>

    <joint name="base_right_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="right_wheel_link" />
        <origin xyz="0 ${-(base_diameter + wheel_length) / 2.0} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_left_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="left_wheel_link" />
        <origin xyz="0 ${(base_diameter + wheel_length) / 2.0} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_caster_wheel_joint" type="fixed">
        <parent link="base_link" />
        <child link="caster_wheel_link" />
        <origin xyz="${base_diameter / 3.0} 0 ${-wheel_radius / 2.0}" rpy="0 0 0" />
    </joint>


</robot>